export const ru: Record<string, string> = {
  "Details to confirm before publishing": "Детали, которые необходимо подтвердить до публикации",
  "Starting from": "От",
  "Departure:": "Отправление:",
  "Main destination": "Основное направление",
  "Duration": "Продолжительность",
  "Start and finish": "Начало и окончание",
  "Price basis": "Расчёт стоимости",
  "Guest numbers": "Количество гостей",
  "Availability": "Доступность",
  "Main activities": "Основные активности",
  "Inclusions": "Включено",
  "Transportation": "Транспорт",
  "Meals / refreshments": "Питание и напитки",
  "Entrance tickets": "Входные билеты",
  "Driver / guide": "Водитель / гид",
  "Recommended clothing / equipment": "Рекомендуемая одежда / снаряжение",
  "Physical activity level": "Уровень физической нагрузки",
  "Age restrictions": "Возрастные ограничения",
  "Exclusions": "Не включено",
  "Anything not specifically listed under Inclusions.": "Всё, что прямо не указано в разделе «Включено».",
  "Request This Package": "Запросить этот пакет",
  "Home": "Главная",
  "Tours": "Туры",
  "Custom Tour": "Индивидуальный тур",
  "Safety": "Безопасность",
  "Contact": "Контакты",
  "Chat on WhatsApp": "Написать в WhatsApp",
  "Women-first care. Everyone is welcome.": "Особая забота о женщинах. Мы рады всем гостям.",
  "Feel safe. See Bali": "Путешествуйте безопасно. Откройте Бали",
  "your way.": "по-своему.",
  "Thoughtful private driving and personalized day tours created to help women feel safe and supported. Couples, male travellers, Indonesian and international guests, and groups of four or more are also welcome, with vehicles arranged to suit the group.": "Продуманные поездки с личным водителем и индивидуальные однодневные туры, созданные, чтобы женщины чувствовали себя безопасно и комфортно. Мы также рады парам, мужчинам, гостям из Индонезии и других стран, а также группам от четырёх человек; транспорт подбирается под размер группы.",
  "Request a Custom Tour Plan": "Запросить индивидуальный маршрут",
  "View Tour Packages": "Посмотреть турпакеты",
  "Travel confidently with Chelyn": "Путешествуйте уверенно вместе с Chelyn",
  "Women-first care": "Особая забота о женщинах",
  "Private · Personal · Flexible": "Приватно · Индивидуально · Гибко",
  "Women-first comfort": "Комфорт женщин прежде всего",
  "All guests welcome": "Мы рады всем гостям",
  "Local and international": "Для местных и иностранных гостей",
  "Vehicles by request": "Транспорт по запросу",
  "About the Tour Service": "О туристическом сервисе",
  "Personal planning with": "Индивидуальное планирование с",
  "local care.": "местной заботой.",
  "Link & Ko Bali is designed especially for women who want to feel comfortable and supported while exploring Bali. The service is also open to couples, male travellers, Indonesian and international guests, and groups from four people. A suitable vehicle can be arranged by request for larger groups.": "Link & Ko Bali создан прежде всего для женщин, которые хотят чувствовать себя комфортно и получать поддержку во время знакомства с Бали. Сервис также открыт для пар, мужчин, местных и иностранных гостей и групп от четырёх человек. Для больших групп по запросу подбирается подходящий транспорт.",
  "Private land transportation is available where specifically stated. Fast boats and some activities may be shared. Before payment, we confirm availability, the itinerary, final price, service format, inclusions, exclusions, and important conditions in writing.": "Индивидуальный наземный транспорт предоставляется там, где это указано. Скоростные лодки и некоторые активности могут быть групповыми. До оплаты мы письменно подтверждаем доступность, маршрут, окончательную цену, формат услуги, включённые и исключённые позиции и важные условия.",
  "Flexible": "Гибко",
  "Choose a package or build a custom day.": "Выберите пакет или составьте индивидуальный день.",
  "Clear": "Понятно",
  "See prices, inclusions, exclusions, and open details.": "Смотрите цены, включённые услуги, исключения и детали, требующие уточнения.",
  "Considered": "Продуманно",
  "Plan around children, elderly guests, access, diet, or special occasions.": "Учитываем детей, пожилых гостей, доступность, питание и особые события.",
  "Inclusive": "Для всех",
  "Women-first care, with all guests welcome.": "Особая забота о женщинах, при этом мы рады всем гостям.",
  "Request a Custom Plan": "Запросить индивидуальный план",
  "Bali Private Transportation": "Индивидуальный транспорт на Бали",
  "Choose the time you need.": "Выберите подходящую продолжительность.",
  "Starting prices help you plan. Your final quote depends on the destination, itinerary, travel distance, and your requirements.": "Начальные цены помогают спланировать бюджет. Итоговая стоимость зависит от направления, маршрута, расстояния и ваших требований.",
  "Independent rental": "Самостоятельная аренда",
  "Local Car Rental": "Аренда автомобиля",
  "Local-area rental service": "Аренда для поездок по местному району",
  "Arrival made simple": "Удобная встреча по прибытии",
  "Airport Transfer": "Трансфер из аэропорта",
  "Starting price for the Kuta area": "Начальная цена для района Кута",
  "A focused itinerary": "Компактный маршрут",
  "Half-Day Private Car": "Личный автомобиль на полдня",
  "Up to 5 hours": "До 5 часов",
  "A full Bali day": "Полный день на Бали",
  "Full-Day Private Car": "Личный автомобиль на полный день",
  "Up to 10 hours": "До 10 часов",
  "Overtime": "Дополнительное время",
  "IDR 35,000 per additional hour": "35 000 IDR за каждый дополнительный час",
  "Package prices can be adjusted depending on the destination, itinerary, travel distance, and the guest’s budget.": "Стоимость пакета может быть скорректирована в зависимости от направления, маршрута, расстояния и бюджета гостя.",
  "Paid separately by the guest": "Оплачивается гостем отдельно",
  "Unless specifically stated as included:": "Если прямо не указано, что включено:",
  "Parking fees": "Парковка",
  "Toll-road fees": "Платные дороги",
  "Meals": "Питание",
  "Activities": "Активности",
  "Vehicle and service details": "Информация о транспорте и услуге",
  "Toyota Raize 2023; other vehicles available by request": "Toyota Raize 2023; другой транспорт доступен по запросу",
  "Maximum four guests with the female-driver service": "До четырёх гостей при услуге с женщиной-водителем",
  "Fuel is included": "Топливо включено",
  "Local service area: Bali, Indonesia": "Местная зона обслуживания: Бали, Индонезия",
  "Nusa Penida Tour Packages": "Турпакеты на Нуса-Пениду",
  "Compare before you choose.": "Сравните перед выбором.",
  "Selected packages depart from Sanur or Matahari Terbit Harbour. The exact meeting point and departure time will be confirmed after booking.": "Некоторые пакеты отправляются из Санура или порта Матахари-Тербит. Точное место встречи и время отправления подтверждаются после бронирования.",
  "Nusa Penida destination gallery": "Галерея Нуса-Пениды",
  "Package": "Пакет",
  "Price": "Цена",
  "Main focus": "Главное",
  "Snorkeling Package": "Пакет со снорклингом",
  "Four snorkeling locations": "Четыре места для снорклинга",
  "Combination West + East": "Запад + Восток",
  "Four island destinations": "Четыре места на острове",
  "West Island Tour": "Тур по западной части острова",
  "West-coast destinations": "Места западного побережья",
  "East Island Tour": "Тур по восточной части острова",
  "East-coast destinations": "Места восточного побережья",
  "Special Package": "Специальный пакет",
  "Snorkeling + west island tour": "Снорклинг + тур по западной части",
  "Separate departure route": "Отдельный маршрут отправления",
  "Serangan Harbour package.": "Пакет с отправлением из порта Серанган.",
  "This package is intentionally listed separately from packages departing from Sanur or Matahari Terbit.": "Этот пакет указан отдельно от пакетов с отправлением из Санура или Матахари-Тербит.",
  "Nusa Penida Snorkeling Package": "Пакет со снорклингом на Нуса-Пениде",
  "A sea-focused Nusa Penida day combining return transfers, four snorkeling locations, and lunch.": "День на Нуса-Пениде с трансфером туда и обратно, четырьмя местами для снорклинга и обедом.",
  "Per person": "За человека",
  "20% discount for children aged 0–3 years": "Скидка 20% для детей от 0 до 3 лет",
  "Selected departures are from Sanur or Matahari Terbit Harbour. The exact meeting point is confirmed after booking.": "Некоторые отправления выполняются из Санура или порта Матахари-Тербит. Точное место встречи подтверждается после бронирования.",
  "Fast-boat journey": "Поездка на скоростной лодке",
  "Snorkeling": "Снорклинг",
  "Lunch": "Обед",
  "Hotel transfer and return fast-boat transfer are listed as included.": "Трансфер из отеля и поездка на скоростной лодке туда и обратно указаны как включённые.",
  "Lunch and mineral water are listed as included.": "Обед и минеральная вода указаны как включённые.",
  "Entrance tickets are not specifically listed as included.": "Входные билеты не указаны как включённые.",
  "English-speaking driver or guide is listed as included.": "Англоговорящий водитель или гид указан как включённый.",
  "Snorkeling locations": "Места для снорклинга",
  "Hotel pickup and drop-off": "Трансфер из отеля и обратно",
  "Return fast-boat transfer": "Скоростная лодка туда и обратно",
  "Snorkeling at four locations": "Снорклинг в четырёх местах",
  "Snorkeling equipment": "Снаряжение для снорклинга",
  "Towel": "Полотенце",
  "English-speaking driver or guide": "Англоговорящий водитель или гид",
  "Insurance coverage": "Страховое покрытие",
  "Mineral water": "Минеральная вода",
  "Snorkeling locations are subject to weather, sea conditions, and safety considerations. Manta sightings cannot be guaranteed.": "Места для снорклинга зависят от погоды, состояния моря и требований безопасности. Встреча с мантами не гарантируется.",
  "Combination West and East One-Day Island Tour": "Однодневный тур по западной и восточной частям острова",
  "A combined sightseeing route covering selected highlights on both the west and east sides of Nusa Penida.": "Комбинированный обзорный маршрут по выбранным достопримечательностям западной и восточной частей Нуса-Пениды.",
  "West and East Nusa Penida": "Западная и восточная Нуса-Пенида",
  "Island sightseeing": "Обзорная поездка по острову",
  "Beach and viewpoint stops": "Остановки у пляжей и смотровых площадок",
  "Hotel transfer, return fast boat, and a private car in Nusa Penida are listed as included.": "Трансфер из отеля, скоростная лодка туда и обратно и личный автомобиль на Нуса-Пениде указаны как включённые.",
  "À la carte lunch and mineral water are listed as included.": "Обед по меню и минеральная вода указаны как включённые.",
  "Entrance fees are listed as included.": "Входные билеты указаны как включённые.",
  "Return hotel transfer": "Трансфер из отеля и обратно",
  "Private car in Nusa Penida": "Личный автомобиль на Нуса-Пениде",
  "À la carte lunch": "Обед по меню",
  "Entrance fees": "Входные билеты",
  "The itinerary may be adjusted because of traffic, weather, harbour operations, road conditions, or safety considerations.": "Маршрут может быть изменён из-за дорожной обстановки, погоды, работы порта, состояния дорог или требований безопасности.",
  "West Nusa Penida Island Tour": "Тур по западной Нуса-Пениде",
  "A west-coast sightseeing route featuring cliffs, natural formations, and Crystal Bay.": "Обзорный маршрут по западному побережью с утёсами, природными образованиями и Кристал-Бэй.",
  "Beach and cliff viewpoints": "Смотровые площадки у пляжей и утёсов",
  "Hotel transfer, return fast boat, and a private car with fuel are listed as included.": "Трансфер из отеля, скоростная лодка туда и обратно и личный автомобиль с топливом указаны как включённые.",
  "Restaurant lunch and mineral water are listed as included.": "Обед в ресторане и минеральная вода указаны как включённые.",
  "Entrance tickets for the listed destinations are included.": "Входные билеты в указанные места включены.",
  "Nusa Penida island tour": "Тур по острову Нуса-Пенида",
  "Lunch at a restaurant": "Обед в ресторане",
  "Private car": "Личный автомобиль",
  "Fuel": "Топливо",
  "Entrance tickets for the listed destinations": "Входные билеты в указанные места",
  "East Nusa Penida Island Tour": "Тур по восточной Нуса-Пениде",
  "An east-coast sightseeing route featuring beaches, the Tree House, and Thousand Islands Viewpoint.": "Обзорный маршрут по восточному побережью с пляжами, Домиком на дереве и смотровой площадкой Thousand Islands.",
  "Nusa Penida Special Package": "Специальный пакет Нуса-Пенида",
  "A combined snorkeling and west-island sightseeing experience for guests who want both sea and land activities.": "Комбинированный пакет со снорклингом и обзорной поездкой по западной части острова для гостей, желающих совместить морские и наземные активности.",
  "Snorkeling and island-tour locations": "Места для снорклинга и поездки по острову",
  "Island tour covering three destinations": "Тур по острову с посещением трёх мест",
  "Snorkeling and island-tour locations may be changed or cancelled because of weather, sea conditions, road conditions, timing, or safety concerns.": "Места для снорклинга и поездки по острову могут быть изменены или отменены из-за погоды, состояния моря и дорог, времени или требований безопасности.",
  "West Nusa Penida Tour from Serangan Harbour": "Тур по западной Нуса-Пениде из порта Серанган",
  "A private one-person west Nusa Penida package departing from Serangan Harbour and arriving at a private jetty.": "Индивидуальный пакет для одного гостя по западной Нуса-Пениде с отправлением из порта Серанган и прибытием на частный причал.",
  "Daily Departure": "Ежедневное отправление",
  "Private package price shown for one guest": "Указана цена индивидуального пакета для одного гостя",
  "One guest at the displayed price; pricing for two or more guests must be confirmed.": "Указанная цена действует для одного гостя; стоимость для двух и более гостей необходимо подтвердить.",
  "Daily departure": "Ежедневное отправление",
  "Beach-club access": "Посещение пляжного клуба",
  "Return boat ticket and a private car in Nusa Penida are included. Hotel transfer is not yet confirmed.": "Билет на лодку туда и обратно и личный автомобиль на Нуса-Пениде включены. Трансфер из отеля пока не подтверждён.",
  "Lunch is listed as included.": "Обед указан как включённый.",
  "Nusa Penida entrance fee is listed as included.": "Входной сбор на Нуса-Пениде указан как включённый.",
  "A driver or guide is not specifically listed and must be confirmed.": "Водитель или гид отдельно не указан; наличие необходимо подтвердить.",
  "Suggested itinerary": "Предлагаемый маршрут",
  "Departure from Serangan Harbour": "Отправление из порта Серанган",
  "Return journey": "Обратная поездка",
  "Return boat ticket from Serangan Harbour to the private jetty in Nusa Penida": "Билет на лодку туда и обратно из порта Серанган до частного причала на Нуса-Пениде",
  "Nusa Penida tour based on the listed itinerary": "Тур по Нуса-Пениде по указанному маршруту",
  "Nusa Penida entrance fee": "Входной сбор на Нуса-Пениде",
  "Complimentary access to Caspla Beach Club": "Бесплатное посещение Caspla Beach Club",
  "Complimentary swimming-pool access": "Бесплатное посещение бассейна",
  "Air-conditioned toilet facilities": "Туалеты с кондиционером",
  "Boat waiting area at the beach club": "Зона ожидания лодки в пляжном клубе",
  "This price is for a private package for one guest.": "Эта цена указана для индивидуального пакета на одного гостя.",
  "Water sports are available at the beach club. Complimentary access is not confirmed.": "В пляжном клубе доступны водные виды спорта. Бесплатное участие не подтверждено.",
  "Kintamani Mount Batur Jeep Experiences": "Джип-туры к горе Батур в Кинтамани",
  "Three ways to see the mountain.": "Три способа увидеть гору.",
  "These are Kintamani jeep experiences only—not complete Bali transportation packages.": "Это только джип-туры в Кинтамани, а не полные транспортные пакеты по Бали.",
  "Private jeep experiences with volcanic views": "Индивидуальные джип-туры с видами на вулкан",
  "One jeep can accommodate a maximum of three guests.": "Один джип вмещает не более трёх гостей.",
  "Prices do not include a full-day private car, hotel transfer, fuel, or a separate driver outside the jeep service.": "Цена не включает личный автомобиль на полный день, трансфер из отеля, топливо или отдельного водителя вне джип-тура.",
  "Afternoon Jeep Trip": "Дневной джип-тур",
  "An afternoon off-road visit to the Black Lava and Black Sand areas.": "Дневная поездка по бездорожью в районы Чёрной лавы и Чёрного песка.",
  "Mount Batur area entrance tickets": "Входные билеты в район горы Батур",
  "Sunset Jeep Trip": "Джип-тур на закате",
  "A sunset-focused jeep experience with Black Lava, Black Sand, coffee, and snacks.": "Джип-тур на закате с посещением Чёрной лавы и Чёрного песка, кофе и закусками.",
  "Sunset Point": "Смотровая площадка на закате",
  "Coffee and snacks": "Кофе и закуски",
  "Sunrise Jeep Trip": "Джип-тур на рассвете",
  "An early-morning jeep experience covering sunrise, Black Lava, coffee, and breakfast.": "Ранний джип-тур с рассветом, Чёрной лавой, кофе и завтраком.",
  "Sunrise viewpoint": "Смотровая площадка на рассвете",
  "Coffee break": "Перерыв на кофе",
  "Breakfast": "Завтрак",
  "Maximum 3 guests": "Максимум 3 гостя",
  "per jeep, net": "за джип, итоговая цена",
  "Duration / schedule": "Продолжительность / расписание",
  "Physical activity": "Физическая нагрузка",
  "Clothing / equipment": "Одежда / снаряжение",
  "Not included": "Не включено",
  "Full-day private car, hotel transfer, fuel, or a separate driver outside the jeep service.": "Личный автомобиль на полный день, трансфер из отеля, топливо и отдельный водитель вне джип-тура.",
  "Comfort beyond the drive": "Комфорт не только в дороге",
  "Personal care for your Bali day": "Личная забота во время вашего дня на Бали",
  "Considered comfort": "Продуманный комфорт",
  "The small things are": "Мы уже позаботились",
  "already handled.": "о мелочах.",
  "Long days feel lighter when useful essentials are within reach.": "Долгие поездки проходят легче, когда всё необходимое под рукой.",
  "Snacks": "Закуски",
  "Phone charger": "Зарядное устройство",
  "Tissues & wet wipes": "Салфетки и влажные салфетки",
  "Umbrella": "Зонт",
  "Small first-aid kit": "Небольшая аптечка",
  "Trash bag": "Пакет для мусора",
  "Sanitary pads are available in the car.": "В автомобиле есть гигиенические прокладки.",
  "A simple comfort detail for guests who need them.": "Небольшая забота для гостей, которым они понадобятся.",
  "Clear before you book": "Всё понятно до бронирования",
  "Payment and policies.": "Оплата и правила.",
  "Review the official payment details, deposit requirements, and cancellation policy before confirming your trip.": "Перед подтверждением поездки ознакомьтесь с официальными реквизитами, условиями депозита и правилами отмены.",
  "Payment Information": "Информация об оплате",
  "Bank": "Банк",
  "Account number": "Номер счёта",
  "Account name": "Имя владельца счёта",
  "For bank-transfer payments, please transfer only to the official Bank Mandiri account listed above.": "При оплате банковским переводом отправляйте средства только на официальный счёт Bank Mandiri, указанный выше.",
  "Deposit": "Депозит",
  "30% to confirm the reservation": "30% для подтверждения бронирования",
  "Remaining balance": "Остаток к оплате",
  "Paid on the day of the trip": "Оплачивается в день поездки",
  "Accepted methods": "Способы оплаты",
  "Bank transfer · Cash · Card · QRIS": "Банковский перевод · Наличные · Карта · QRIS",
  "Payment security": "Безопасность оплаты",
  "For your safety, do not transfer money to any other bank account. Please contact us through our official WhatsApp number if you receive different payment instructions.": "В целях безопасности не переводите деньги на другие банковские счета. Если вы получили иные платёжные инструкции, свяжитесь с нами по официальному номеру WhatsApp.",
  "Cancellation and Rescheduling": "Отмена и перенос",
  "More than 72 hours before the trip": "Более чем за 72 часа до поездки",
  "The deposit is refundable.": "Депозит возвращается.",
  "Within 72 hours of the trip": "Менее чем за 72 часа до поездки",
  "The deposit is non-refundable.": "Депозит не возвращается.",
  "Rescheduling": "Перенос даты",
  "Allowed, subject to availability.": "Возможен при наличии свободных мест.",
  "Important Guest Information": "Важная информация для гостей",
  "Know what to expect before you book.": "Узнайте важные детали до бронирования.",
  "These details form the practical booking guide. Items still awaiting confirmation are clearly marked and will not be presented as final policy.": "Эти сведения являются практическим руководством по бронированию. Пункты, ожидающие подтверждения, чётко отмечены и не представляются как окончательные правила.",
  "Booking and confirmation": "Бронирование и подтверждение",
  "Submit a package or custom-tour request through the form or official WhatsApp number.": "Отправьте запрос на пакет или индивидуальный тур через форму или официальный номер WhatsApp.",
  "We will confirm availability, the final itinerary, price, inclusions, exclusions, and pickup details in writing.": "Мы письменно подтвердим доступность, окончательный маршрут, цену, включённые и исключённые услуги и детали трансфера.",
  "A 30% deposit is required to confirm the reservation. The remaining balance is due on the day of the trip.": "Для подтверждения бронирования требуется депозит 30%. Остаток оплачивается в день поездки.",
  "Messages are answered during business hours, 9:00 AM–9:00 PM Bali time (WITA).": "Мы отвечаем на сообщения в рабочие часы: с 09:00 до 21:00 по времени Бали (WITA).",
  "Changes, refunds, and timing": "Изменения, возвраты и сроки",
  "Cancellation more than 72 hours before the trip: the deposit is refundable.": "При отмене более чем за 72 часа до поездки депозит возвращается.",
  "Cancellation within 72 hours: the deposit is non-refundable.": "При отмене менее чем за 72 часа депозит не возвращается.",
  "Rescheduling is allowed, subject to availability.": "Перенос возможен при наличии свободных мест.",
  "Pickup and preparation": "Трансфер и подготовка",
  "The exact pickup point and departure details will be confirmed after booking.": "Точное место трансфера и детали отправления подтверждаются после бронирования.",
  "Bring suitable clothing and footwear, sun protection, required personal medication, and activity-specific equipment when advised.": "Возьмите подходящую одежду и обувь, защиту от солнца, необходимые личные лекарства и специальное снаряжение, если это рекомендовано.",
  "Accessibility, language, and food": "Доступность, языки и питание",
  "Disclose medical, mobility, pregnancy, allergy, accessibility, and dietary requirements before confirmation.": "До подтверждения сообщите о медицинских состояниях, ограничениях подвижности, беременности, аллергиях, требованиях доступности и питания.",
  "English, Indonesian, Simplified Chinese, Russian, Japanese, and Korean are available.": "Доступны английский, индонезийский, упрощённый китайский, русский, японский и корейский языки.",
  "Photography and belongings": "Фотографии и личные вещи",
  "Guests are responsible for personal belongings unless otherwise required by applicable law.": "Гости несут ответственность за личные вещи, если применимое законодательство не требует иного.",
  "Contact and emergencies": "Контакты и экстренные ситуации",
  "Official WhatsApp and phone: +62 859-5931-3339.": "Официальный WhatsApp и телефон: +62 859-5931-3339.",
  "Emergency contact: Chelyn, +62 858-2375-4807.": "Экстренный контакт: Chelyn, +62 858-2375-4807.",
  "Business hours: 9:00 AM–9:00 PM Bali time (WITA).": "Рабочие часы: 09:00–21:00 по времени Бали (WITA).",
  "Messages are answered during business hours.": "Мы отвечаем на сообщения в рабочие часы.",
  "Guest Safety Information": "Информация о безопасности гостей",
  "Good trips start with clear expectations.": "Хорошее путешествие начинается с ясных ожиданий.",
  "Please read this information before requesting or confirming a service.": "Прочитайте эту информацию до запроса или подтверждения услуги.",
  "Guests must follow the instructions of the driver, guide, boat crew, activity operator, and local authorities.": "Гости обязаны следовать инструкциям водителя, гида, экипажа лодки, организатора активности и местных властей.",
  "Tour schedules and destinations may change because of weather, sea conditions, traffic, road conditions, harbour operations, volcanic activity, government restrictions, or other safety concerns.": "Расписание и места посещения могут измениться из-за погоды, состояния моря, дорожной обстановки, состояния дорог, работы порта, вулканической активности, государственных ограничений или других требований безопасности.",
  "Guests must disclose relevant medical conditions, allergies, injuries, pregnancy, mobility limitations, or other health concerns before participating.": "До участия гости обязаны сообщить о важных медицинских состояниях, аллергиях, травмах, беременности, ограничениях подвижности или других проблемах со здоровьем.",
  "Guests must bring their own personal medication.": "Гости должны иметь при себе личные лекарства.",
  "Children must remain under the supervision of a parent or responsible adult.": "Дети должны постоянно находиться под присмотром родителя или ответственного взрослого.",
  "Guests should wear suitable clothing and footwear for the selected activities.": "Гостям следует надевать подходящую одежду и обувь для выбранных активностей.",
  "Safety equipment must be worn when required.": "При необходимости защитное снаряжение обязательно к использованию.",
  "Alcohol use or unsafe behaviour may result in removal from an activity.": "Употребление алкоголя или опасное поведение может привести к отстранению от активности.",
  "Snorkeling locations and manta sightings cannot be guaranteed.": "Места для снорклинга и встреча с мантами не гарантируются.",
  "The operator may refuse participation when a guest’s health, condition, or behaviour creates a safety risk.": "Организатор может отказать в участии, если здоровье, состояние или поведение гостя создаёт риск для безопасности.",
  "Emergency contact during the tour: Chelyn, +62 858-2375-4807.": "Экстренный контакт во время тура: Chelyn, +62 858-2375-4807.",
  "Travel insurance is recommended.": "Рекомендуется туристическая страховка.",
  "Some package cards list insurance coverage, but the provider, benefits, limits, and exclusions must be confirmed. [ADD INSURANCE INFORMATION]": "В некоторых пакетах указано страховое покрытие, однако необходимо подтвердить страховщика, преимущества, лимиты и исключения. [ДОБАВИТЬ ИНФОРМАЦИЮ О СТРАХОВКЕ]",
  "Sea conditions, harbour operations, steep or uneven access, cliffs, and road conditions may affect the itinerary or whether a stop is suitable.": "Состояние моря, работа порта, крутые или неровные проходы, утёсы и состояние дорог могут повлиять на маршрут и возможность посещения остановки.",
  "Mount Batur jeep experiences": "Джип-туры к горе Батур",
  "Off-road terrain can be rough. Guests who are pregnant or have back, joint, mobility, or other medical concerns must disclose them before booking.": "Бездорожье может быть неровным. Беременные гости и гости с проблемами спины, суставов, подвижности или другими медицинскими состояниями должны сообщить об этом до бронирования.",
  "Emergency and insurance": "Экстренные ситуации и страховка",
  "Emergency: Chelyn, +62 858-2375-4807. Travel insurance is recommended; confirm any package-specific coverage in writing before booking.": "Экстренный контакт: Chelyn, +62 858-2375-4807. Рекомендуется туристическая страховка; до бронирования письменно подтвердите любое покрытие, связанное с конкретным пакетом.",
  "Reviews and Trust": "Отзывы и доверие",
  "Only verified information belongs here.": "Здесь публикуется только проверенная информация.",
  "Reviews, credentials, certifications, and partner details will be published only after they can be verified.": "Отзывы, документы, сертификаты и сведения о партнёрах публикуются только после проверки.",
  "Guest reviews": "Отзывы гостей",
  "No testimonials have been invented or published without a source.": "Мы не придумываем и не публикуем отзывы без подтверждённого источника.",
  "Local perspective": "Местный взгляд",
  "Chelyn plans each route around the guest’s timing, interests, comfort, and safety needs.": "Chelyn планирует каждый маршрут с учётом времени, интересов, комфорта и безопасности гостя.",
  "Credentials and partners": "Документы и партнёры",
  "Business or partner claims will remain unpublished until documentation is available.": "Заявления о бизнесе или партнёрстве не публикуются до получения подтверждающих документов.",
  "Bank transfers must go only to the official Bank Mandiri account displayed in the Payment Information section.": "Банковские переводы следует отправлять только на официальный счёт Bank Mandiri, указанный в разделе «Информация об оплате».",
  "Review payment details": "Проверить платёжные реквизиты",
  "Contact Link & Ko Bali": "Связаться с Link & Ko Bali",
  "Tell us what you want to experience.": "Расскажите, что вы хотите увидеть и попробовать.",
  "Share your preferred destinations, schedule, group size, and interests. We will create a personalized day-tour plan for you.": "Сообщите желаемые места, расписание, размер группы и интересы. Мы составим для вас индивидуальный план однодневного тура.",
  "International WhatsApp": "Международный WhatsApp",
  "Indonesia / Tamu lokal": "Индонезия / местные гости",
  "Email": "Электронная почта",
  "Business hours": "Рабочие часы",
  "9:00 AM–9:00 PM Bali time (WITA)": "09:00–21:00 по времени Бали (WITA)",
  "Expected response": "Время ответа",
  "Messages are answered during business hours": "Мы отвечаем на сообщения в рабочие часы",
  "Service area": "Зона обслуживания",
  "Bali, including selected Nusa Penida and Kintamani services": "Бали, включая отдельные услуги на Нуса-Пениде и в Кинтамани",
  "Emergency contact": "Экстренный контакт",
  "Connect With Us": "Свяжитесь с нами",
  "Scan an official QR code below. Tap or click any image to open it at full size.": "Отсканируйте официальный QR-код ниже. Нажмите на изображение, чтобы открыть его в полном размере.",
  "Scan to start a WhatsApp chat with us.": "Отсканируйте, чтобы начать чат с нами в WhatsApp.",
  "Scan to connect with us on WeChat.": "Отсканируйте, чтобы связаться с нами в WeChat.",
  "Scan to follow us on RedNote.": "Отсканируйте, чтобы подписаться на нас в RedNote.",
  "Scan to follow us on Instagram.": "Отсканируйте, чтобы подписаться на нас в Instagram.",
  "Open full size ↗": "Открыть в полном размере ↗",
  "Good questions": "Полезные вопросы",
  "Before you": "Перед тем как",
  "make a request.": "отправить запрос.",
  "Anything not covered here can be confirmed directly with Chelyn.": "Всё, что здесь не указано, можно уточнить напрямую у Chelyn.",
  "Can I customize a tour?": "Можно ли составить индивидуальный тур?",
  "Yes. Share your preferred destinations, dates, available time, group size, interests, budget, and any special requirements. We will prepare a suitable plan and confirm the final details in writing.": "Да. Сообщите желаемые места, даты, доступное время, размер группы, интересы, бюджет и особые требования. Мы подготовим подходящий план и письменно подтвердим окончательные детали.",
  "Are the tours private?": "Туры индивидуальные?",
  "Private land transportation is available where it is specifically listed. Fast boats and some activities may be shared. [CONFIRM WHICH PACKAGES ARE FULLY PRIVATE OR SHARED]": "Индивидуальный наземный транспорт предоставляется там, где это прямо указано. Скоростные лодки и некоторые активности могут быть групповыми. [ПОДТВЕРДИТЬ, КАКИЕ ПАКЕТЫ ПОЛНОСТЬЮ ИНДИВИДУАЛЬНЫЕ ИЛИ ГРУППОВЫЕ]",
  "What is included in the price?": "Что входит в цену?",
  "Each package card lists its confirmed inclusions. Your written quotation will confirm transportation, meals, tickets, guide service, and any other inclusions before payment.": "В карточке каждого пакета перечислены подтверждённые включённые услуги. До оплаты в письменном предложении будут подтверждены транспорт, питание, билеты, услуги гида и другие включённые позиции.",
  "Are there additional charges?": "Есть ли дополнительные расходы?",
  "Unless specifically included, parking, toll-road fees, meals, activities, and entrance tickets are paid separately by the guest. Any other extra cost must be confirmed in the written quotation.": "Если иное прямо не указано, парковка, платные дороги, питание, активности и входные билеты оплачиваются гостем отдельно. Любые дополнительные расходы должны быть подтверждены в письменном предложении.",
  "Is transportation included?": "Транспорт включён?",
  "It depends on the package. Only transportation specifically listed under Inclusions is included. Hotel pickup areas and exact meeting points may still require confirmation.": "Это зависит от пакета. Включён только транспорт, прямо указанный в разделе «Включено». Районы трансфера из отеля и точные места встречи могут потребовать подтверждения.",
  "Where will I be picked up?": "Где меня заберут?",
  "Enter your hotel or pickup location in the request form. We will confirm the pickup point, coverage area, and any extra transfer cost before your booking is confirmed.": "Укажите отель или место трансфера в форме запроса. До подтверждения бронирования мы уточним место встречи, зону обслуживания и возможную доплату за трансфер.",
  "Can children join?": "Можно ли участвовать детям?",
  "Children may join suitable tours under adult supervision. Some Nusa Penida packages list a 20% discount for children aged 0–3. [ADD CHILD-SEAT AVAILABILITY] [CONFIRM ACTIVITY-SPECIFIC AGE RESTRICTIONS]": "Дети могут участвовать в подходящих турах под присмотром взрослых. Для некоторых пакетов на Нуса-Пениду указана скидка 20% для детей 0–3 лет. [ДОБАВИТЬ ИНФОРМАЦИЮ О ДЕТСКОМ КРЕСЛЕ] [ПОДТВЕРДИТЬ ВОЗРАСТНЫЕ ОГРАНИЧЕНИЯ ДЛЯ АКТИВНОСТЕЙ]",
  "Are the tours suitable for elderly guests?": "Подходят ли туры пожилым гостям?",
  "Suitability depends on the route, access conditions, and the guest’s mobility and health. Disclose any mobility or medical requirements so we can assess the itinerary before confirmation.": "Подходящий формат зависит от маршрута, условий доступа, подвижности и здоровья гостя. Сообщите о медицинских требованиях или ограничениях подвижности, чтобы мы оценили маршрут до подтверждения.",
  "What happens during bad weather?": "Что происходит при плохой погоде?",
  "Routes, activities, or departure points may change for safety. [ADD WEATHER CANCELLATION, RESCHEDULING, AND REFUND POLICY]": "Маршруты, активности или места отправления могут измениться ради безопасности. [ДОБАВИТЬ ПРАВИЛА ОТМЕНЫ ИЗ-ЗА ПОГОДЫ, ПЕРЕНОСА И ВОЗВРАТА]",
  "What should I wear?": "Что надеть?",
  "Wear suitable clothing and secure footwear for the selected activities. Bring sun protection and any personal medication. Package-specific equipment requirements must be confirmed before departure.": "Наденьте подходящую одежду и надёжную обувь для выбранных активностей. Возьмите защиту от солнца и личные лекарства. Требования к снаряжению для конкретного пакета необходимо подтвердить до отправления.",
  "Do I need travel insurance?": "Нужна ли туристическая страховка?",
  "Travel insurance is recommended. Some packages list insurance coverage, but the provider, benefits, exclusions, and limits still require confirmation. [ADD GENERAL INSURANCE INFORMATION]": "Туристическая страховка рекомендуется. В некоторых пакетах указано страховое покрытие, но страховщик, преимущества, исключения и лимиты требуют подтверждения. [ДОБАВИТЬ ОБЩУЮ ИНФОРМАЦИЮ О СТРАХОВКЕ]",
  "Can you accommodate dietary restrictions?": "Можно ли учесть ограничения в питании?",
  "Tell us about allergies, dietary restrictions, or preferences in the request form. We will confirm what can be accommodated before the trip.": "Укажите аллергии, ограничения или предпочтения в питании в форме запроса. До поездки мы подтвердим, что можно организовать.",
  "How do I pay?": "Как оплатить?",
  "A 30% deposit confirms the reservation. The remaining balance is due on the trip day. Accepted methods are bank transfer, cash, card, and QRIS. Bank transfers must go only to the official Bank Mandiri account shown on this website.": "Депозит 30% подтверждает бронирование. Остаток оплачивается в день поездки. Принимаются банковский перевод, наличные, карта и QRIS. Банковские переводы следует отправлять только на официальный счёт Bank Mandiri, указанный на этом сайте.",
  "What is the cancellation policy?": "Каковы правила отмены?",
  "The deposit is refundable when cancellation is made more than 72 hours before the trip. Within 72 hours, the deposit is non-refundable. Rescheduling is allowed subject to availability; any fee or deadline still needs confirmation.": "При отмене более чем за 72 часа до поездки депозит возвращается. При отмене менее чем за 72 часа депозит не возвращается. Перенос возможен при наличии свободных мест; возможные сборы и сроки требуют подтверждения.",
  "How quickly will I receive my custom plan?": "Как быстро я получу индивидуальный план?",
  "We review requests and reply through WhatsApp or email during business hours, 9:00 AM–9:00 PM Bali time (WITA).": "Мы рассматриваем запросы и отвечаем через WhatsApp или электронную почту в рабочие часы: 09:00–21:00 по времени Бали (WITA).",
  "Plan Your Bali Trip With Us": "Спланируйте путешествие по Бали вместе с нами",
  "Tell us what": "Расскажите, что нужно",
  "your trip needs.": "для вашей поездки.",
  "Every guest travels differently. Tell us your preferred destinations, available dates, group size, interests, and budget. We will help arrange a personalized itinerary based on your needs.": "Каждый гость путешествует по-своему. Сообщите желаемые места, доступные даты, размер группы, интересы и бюджет. Мы поможем составить индивидуальный маршрут под ваши потребности.",
  "Preferred destinations and activities": "Желаемые места и активности",
  "Available time and travel schedule": "Доступное время и расписание поездки",
  "Group size and estimated budget": "Размер группы и примерный бюджет",
  "Children, elderly guests, and accessibility requirements": "Дети, пожилые гости и требования доступности",
  "Pickup and drop-off locations": "Места трансфера и высадки",
  "Dietary needs and special occasions": "Питание и особые события",
  "Messages are answered from 9:00 AM to 9:00 PM Bali time (WITA).": "Мы отвечаем на сообщения с 09:00 до 21:00 по времени Бали (WITA).",
  "Thank you for contacting Link & Ko Bali.": "Спасибо, что связались с Link & Ko Bali.",
  "We will review your request and contact you through WhatsApp or email.": "Мы рассмотрим запрос и свяжемся с вами через WhatsApp или электронную почту.",
  "WhatsApp has opened with your request details. Tap Send in WhatsApp to complete your inquiry.": "WhatsApp открыт с данными вашего запроса. Нажмите «Отправить» в WhatsApp, чтобы завершить обращение.",
  "Send another request": "Отправить ещё один запрос",
  "Selected package": "Выбранный пакет",
  "Full name": "Полное имя",
  "WhatsApp number": "Номер WhatsApp",
  "Email address": "Электронная почта",
  "Travel date": "Дата поездки",
  "Number of adults": "Количество взрослых",
  "Number and ages of children": "Количество и возраст детей",
  "Hotel or pickup location": "Отель или место трансфера",
  "Drop-off location": "Место высадки",
  "Available time or schedule": "Доступное время или расписание",
  "Preferred destinations": "Желаемые места",
  "Estimated budget": "Примерный бюджет",
  "Transportation requirements": "Требования к транспорту",
  "Dietary requirements": "Требования к питанию",
  "Medical or mobility considerations": "Медицинские особенности или ограничения подвижности",
  "Special occasion": "Особое событие",
  "Additional requests": "Дополнительные пожелания",
  "Example: 2 children, ages 3 and 7": "Например: 2 ребёнка, 3 и 7 лет",
  "Same as pickup, or another location": "То же место или другой адрес",
  "Example: 8:00 AM–6:00 PM": "Например: 08:00–18:00",
  "Places or package you are interested in": "Интересующие места или пакет",
  "Snorkeling, beach, temple, food, photography…": "Снорклинг, пляж, храм, еда, фотография…",
  "Airport transfer, half day, full day…": "Трансфер из аэропорта, полдня, полный день…",
  "Allergies or preferences": "Аллергии или предпочтения",
  "Tell us what support you need": "Расскажите, какая поддержка вам нужна",
  "Birthday, honeymoon, proposal, or celebration": "День рождения, медовый месяц, предложение или праздник",
  "Anything else we should know?": "Что ещё нам следует знать?",
  "I confirm that I have read the safety information and have disclosed any relevant medical, mobility, or accessibility requirements.": "Я подтверждаю, что прочитал(а) информацию о безопасности и сообщил(а) о важных медицинских особенностях, ограничениях подвижности или требованиях доступности.",
  "Before submitting": "Перед отправкой",
  "Unless specifically included in your final written quotation, additional costs and services remain excluded.": "Если дополнительные расходы и услуги прямо не включены в окончательное письменное предложение, они оплачиваются отдельно.",
  "Request My Custom Plan": "Запросить индивидуальный план",
  "Submitting this form opens WhatsApp with your details. Your reservation is not confirmed until availability, price, and the deposit are confirmed.": "После отправки формы откроется WhatsApp с вашими данными. Бронирование не подтверждено, пока не согласованы доступность, цена и депозит.",
  "Ready to Plan Your Bali Experience?": "Готовы спланировать путешествие по Бали?",
  "Let’s turn your list into a realistic Bali plan.": "Превратим ваш список желаний в реалистичный план по Бали.",
  "Tell us where you would like to go, how many people are travelling, and your preferred budget. We will help create a suitable plan for your Bali trip.": "Расскажите, куда вы хотите поехать, сколько человек путешествует и какой у вас бюджет. Мы поможем составить подходящий план поездки по Бали.",
  "Private trips with Chelyn.": "Индивидуальные поездки с Chelyn.",
  "Packages": "Пакеты",
};

export const ruPending: Record<string, string> = {
  "ADD DURATION": "ДОБАВИТЬ ПРОДОЛЖИТЕЛЬНОСТЬ",
  "ADD STARTING AND FINISHING TIME": "ДОБАВИТЬ ВРЕМЯ НАЧАЛА И ОКОНЧАНИЯ",
  "CONFIRM WHETHER PRICE IS PER PERSON OR PER GROUP": "ПОДТВЕРДИТЬ, УКАЗАНА ЛИ ЦЕНА ЗА ЧЕЛОВЕКА ИЛИ ЗА ГРУППУ",
  "ADD MINIMUM AND MAXIMUM NUMBER OF GUESTS": "ДОБАВИТЬ МИНИМАЛЬНОЕ И МАКСИМАЛЬНОЕ КОЛИЧЕСТВО ГОСТЕЙ",
  "ADD OPERATING DAYS": "ДОБАВИТЬ ДНИ РАБОТЫ",
  "ADD RECOMMENDED CLOTHING OR EQUIPMENT": "ДОБАВИТЬ РЕКОМЕНДУЕМУЮ ОДЕЖДУ ИЛИ СНАРЯЖЕНИЕ",
  "ADD PHYSICAL ACTIVITY LEVEL": "ДОБАВИТЬ УРОВЕНЬ ФИЗИЧЕСКОЙ НАГРУЗКИ",
  "ADD AGE RESTRICTIONS, IF APPLICABLE": "ДОБАВИТЬ ВОЗРАСТНЫЕ ОГРАНИЧЕНИЯ, ЕСЛИ ПРИМЕНИМО",
  "CONFIRM DEPARTURE HARBOUR": "ПОДТВЕРДИТЬ ПОРТ ОТПРАВЛЕНИЯ",
  "CONFIRM HOTEL PICKUP AREAS": "ПОДТВЕРДИТЬ РАЙОНЫ ТРАНСФЕРА ИЗ ОТЕЛЯ",
  "CONFIRM INSURANCE COVERAGE DETAILS": "ПОДТВЕРДИТЬ ДЕТАЛИ СТРАХОВОГО ПОКРЫТИЯ",
  "CONFIRM WHETHER A RESCHEDULING FEE OR TIME LIMIT APPLIES": "ПОДТВЕРДИТЬ СБОР ИЛИ СРОК ДЛЯ ПЕРЕНОСА",
  "ADD EMAIL ADDRESS": "ДОБАВИТЬ АДРЕС ЭЛЕКТРОННОЙ ПОЧТЫ",
};
