export const zh: Record<string, string> = {
  "Details to confirm before publishing": "发布前需要确认的详情",
  "Starting from": "起价",
  "Departure:": "出发：",
  "Main destination": "主要目的地",
  "Duration": "时长",
  "Start and finish": "开始与结束时间",
  "Price basis": "计价方式",
  "Guest numbers": "游客人数",
  "Availability": "开放时间",
  "Main activities": "主要活动",
  "Inclusions": "费用包含",
  "Transportation": "交通",
  "Meals / refreshments": "餐食与饮品",
  "Entrance tickets": "门票",
  "Driver / guide": "司机／导游",
  "Recommended clothing / equipment": "建议服装／装备",
  "Physical activity level": "体力强度",
  "Age restrictions": "年龄限制",
  "Exclusions": "费用不含",
  "Anything not specifically listed under Inclusions.": "未在费用包含中明确列出的任何项目。",
  "Request This Package": "咨询此套餐",
  "Home": "首页",
  "Tours": "行程",
  "Custom Tour": "定制行程",
  "Safety": "安全须知",
  "Contact": "联系我们",
  "Chat on WhatsApp": "通过 WhatsApp 咨询",
  "Women-first care. Everyone is welcome.": "优先照顾女性，也欢迎每一位游客。",
  "Feel safe. See Bali": "安心探索巴厘岛",
  "your way.": "按你喜欢的方式。",
  "Thoughtful private driving and personalized day tours created to help women feel safe and supported. Couples, male travellers, Indonesian and international guests, and groups of four or more are also welcome, with vehicles arranged to suit the group.": "贴心的私人用车和定制一日游，让女性在旅途中感到安心并获得支持。我们也欢迎情侣、男性游客、印尼本地与国际游客，以及四人或以上的团体，并会按人数安排合适车辆。",
  "Request a Custom Tour Plan": "申请定制行程",
  "View Tour Packages": "查看旅游套餐",
  "Travel confidently with Chelyn": "与 Chelyn 安心游巴厘岛",
  "Women-first care": "女性优先照顾",
  "Private · Personal · Flexible": "私享 · 个性化 · 灵活",
  "Women-first comfort": "女性优先的舒适体验",
  "All guests welcome": "欢迎所有游客",
  "Local and international": "本地与国际游客",
  "Vehicles by request": "可按需求安排车辆",
  "About the Tour Service": "关于旅游服务",
  "Personal planning with": "个性化规划，配合",
  "local care.": "贴心的本地服务。",
  "Link & Ko Bali is designed especially for women who want to feel comfortable and supported while exploring Bali. The service is also open to couples, male travellers, Indonesian and international guests, and groups from four people. A suitable vehicle can be arranged by request for larger groups.": "Link & Ko Bali 特别为希望安心、舒适探索巴厘岛的女性而设计。服务也面向情侣、男性游客、印尼本地与国际游客，以及四人起的团体。人数较多时可按需求安排合适车辆。",
  "Private land transportation is available where specifically stated. Fast boats and some activities may be shared. Before payment, we confirm availability, the itinerary, final price, service format, inclusions, exclusions, and important conditions in writing.": "如套餐明确说明，可提供私人陆路交通。快艇和部分活动可能与其他游客共享。付款前，我们会以书面方式确认名额、行程、最终价格、服务形式、包含与不含项目及重要条款。",
  "Flexible": "灵活",
  "Choose a package or build a custom day.": "选择现有套餐，或定制专属一日行程。",
  "Clear": "清晰透明",
  "See prices, inclusions, exclusions, and open details.": "清楚查看价格、包含、不含及待确认详情。",
  "Considered": "贴心周到",
  "Plan around children, elderly guests, access, diet, or special occasions.": "可根据儿童、长者、无障碍、饮食或特别纪念日需求规划。",
  "Inclusive": "包容友好",
  "Women-first care, with all guests welcome.": "优先照顾女性，同时欢迎所有游客。",
  "Request a Custom Plan": "申请定制方案",
  "Bali Private Transportation": "巴厘岛私人用车",
  "Choose the time you need.": "按你需要的时长选择。",
  "Starting prices help you plan. Your final quote depends on the destination, itinerary, travel distance, and your requirements.": "起价可帮助你规划预算。最终报价取决于目的地、行程、距离和具体需求。",
  "Independent rental": "自驾租车",
  "Local Car Rental": "本地租车",
  "Local-area rental service": "巴厘岛本地租车服务",
  "Arrival made simple": "轻松抵达",
  "Airport Transfer": "机场接送",
  "Starting price for the Kuta area": "库塔地区起价",
  "A focused itinerary": "精简行程",
  "Half-Day Private Car": "半日私人用车",
  "Up to 5 hours": "最长 5 小时",
  "A full Bali day": "畅游巴厘岛一整天",
  "Full-Day Private Car": "全日私人用车",
  "Up to 10 hours": "最长 10 小时",
  "Overtime": "超时费用",
  "IDR 35,000 per additional hour": "每增加 1 小时 35,000 印尼盾",
  "Package prices can be adjusted depending on the destination, itinerary, travel distance, and the guest’s budget.": "套餐价格可根据目的地、行程、距离和游客预算调整。",
  "Paid separately by the guest": "由游客另行支付",
  "Unless specifically stated as included:": "除非套餐明确说明已包含：",
  "Parking fees": "停车费",
  "Toll-road fees": "高速公路费",
  "Meals": "餐食",
  "Activities": "活动",
  "Vehicle and service details": "车辆与服务详情",
  "Toyota Raize 2023; other vehicles available by request": "2023 款 Toyota Raize；其他车型可按需求安排",
  "Maximum four guests with the female-driver service": "女性司机服务最多接待 4 位游客",
  "Fuel is included": "包含燃油",
  "Local service area: Bali, Indonesia": "本地服务区域：印度尼西亚巴厘岛",
  "Nusa Penida Tour Packages": "佩尼达岛旅游套餐",
  "Compare before you choose.": "比较后再选择。",
  "Selected packages depart from Sanur or Matahari Terbit Harbour. The exact meeting point and departure time will be confirmed after booking.": "部分套餐从沙努尔或 Matahari Terbit 港口出发。预订后将确认准确集合地点和出发时间。",
  "Nusa Penida destination gallery": "佩尼达岛景点图片",
  "Package": "套餐",
  "Price": "价格",
  "Main focus": "主要体验",
  "Snorkeling Package": "浮潜套餐",
  "Four snorkeling locations": "四个浮潜点",
  "Combination West + East": "西线＋东线组合",
  "Four island destinations": "四个岛上景点",
  "West Island Tour": "西线环岛游",
  "West-coast destinations": "西海岸景点",
  "East Island Tour": "东线环岛游",
  "East-coast destinations": "东海岸景点",
  "Special Package": "特别套餐",
  "Snorkeling + west island tour": "浮潜＋西线环岛游",
  "Separate departure route": "独立出发路线",
  "Serangan Harbour package.": "Serangan 港口出发套餐。",
  "This package is intentionally listed separately from packages departing from Sanur or Matahari Terbit.": "此套餐与从沙努尔或 Matahari Terbit 出发的套餐分开列出。",
  "Nusa Penida Snorkeling Package": "佩尼达岛浮潜套餐",
  "A sea-focused Nusa Penida day combining return transfers, four snorkeling locations, and lunch.": "以海上体验为主的佩尼达岛一日游，包含往返接送、四个浮潜点和午餐。",
  "Per person": "每人",
  "20% discount for children aged 0–3 years": "0–3 岁儿童享 20% 优惠",
  "Selected departures are from Sanur or Matahari Terbit Harbour. The exact meeting point is confirmed after booking.": "部分班次从沙努尔或 Matahari Terbit 港口出发，预订后确认准确集合地点。",
  "Fast-boat journey": "快艇行程",
  "Snorkeling": "浮潜",
  "Lunch": "午餐",
  "Hotel transfer and return fast-boat transfer are listed as included.": "列明包含酒店接送和往返快艇。",
  "Lunch and mineral water are listed as included.": "列明包含午餐和矿泉水。",
  "Entrance tickets are not specifically listed as included.": "门票未明确列为包含项目。",
  "English-speaking driver or guide is listed as included.": "列明包含英语司机或导游。",
  "Snorkeling locations": "浮潜地点",
  "Hotel pickup and drop-off": "酒店接送",
  "Return fast-boat transfer": "往返快艇",
  "Snorkeling at four locations": "四个地点浮潜",
  "Snorkeling equipment": "浮潜装备",
  "Towel": "毛巾",
  "English-speaking driver or guide": "英语司机或导游",
  "Insurance coverage": "保险保障",
  "Mineral water": "矿泉水",
  "Snorkeling locations are subject to weather, sea conditions, and safety considerations. Manta sightings cannot be guaranteed.": "浮潜地点会根据天气、海况和安全因素调整，无法保证看到魔鬼鱼。",
  "Combination West and East One-Day Island Tour": "佩尼达岛西线＋东线组合一日游",
  "A combined sightseeing route covering selected highlights on both the west and east sides of Nusa Penida.": "组合观光路线，涵盖佩尼达岛西部与东部的精选景点。",
  "West and East Nusa Penida": "佩尼达岛西线与东线",
  "Island sightseeing": "环岛观光",
  "Beach and viewpoint stops": "海滩与观景点停留",
  "Hotel transfer, return fast boat, and a private car in Nusa Penida are listed as included.": "列明包含酒店接送、往返快艇和佩尼达岛私人用车。",
  "À la carte lunch and mineral water are listed as included.": "列明包含单点午餐和矿泉水。",
  "Entrance fees are listed as included.": "列明包含景点门票。",
  "Return hotel transfer": "酒店往返接送",
  "Private car in Nusa Penida": "佩尼达岛私人用车",
  "À la carte lunch": "单点午餐",
  "Entrance fees": "入场费",
  "The itinerary may be adjusted because of traffic, weather, harbour operations, road conditions, or safety considerations.": "行程可能因交通、天气、港口运营、道路状况或安全因素调整。",
  "West Nusa Penida Island Tour": "佩尼达岛西线游",
  "A west-coast sightseeing route featuring cliffs, natural formations, and Crystal Bay.": "西海岸观光路线，包含悬崖、自然地貌和水晶湾。",
  "Beach and cliff viewpoints": "海滩与悬崖观景点",
  "Hotel transfer, return fast boat, and a private car with fuel are listed as included.": "列明包含酒店接送、往返快艇及含燃油的私人用车。",
  "Restaurant lunch and mineral water are listed as included.": "列明包含餐厅午餐和矿泉水。",
  "Entrance tickets for the listed destinations are included.": "包含所列景点的门票。",
  "Nusa Penida island tour": "佩尼达岛环岛游",
  "Lunch at a restaurant": "餐厅午餐",
  "Private car": "私人用车",
  "Fuel": "燃油",
  "Entrance tickets for the listed destinations": "所列景点门票",
  "East Nusa Penida Island Tour": "佩尼达岛东线游",
  "An east-coast sightseeing route featuring beaches, the Tree House, and Thousand Islands Viewpoint.": "东海岸观光路线，包含海滩、树屋和千岛观景台。",
  "Nusa Penida Special Package": "佩尼达岛特别套餐",
  "A combined snorkeling and west-island sightseeing experience for guests who want both sea and land activities.": "浮潜与西线观光组合体验，适合希望同时体验海上和陆地活动的游客。",
  "Snorkeling and island-tour locations": "浮潜与环岛游地点",
  "Island tour covering three destinations": "环岛游涵盖三个景点",
  "Snorkeling and island-tour locations may be changed or cancelled because of weather, sea conditions, road conditions, timing, or safety concerns.": "浮潜或环岛游地点可能因天气、海况、道路、时间或安全因素更改或取消。",
  "West Nusa Penida Tour from Serangan Harbour": "Serangan 港口出发的佩尼达岛西线游",
  "A private one-person west Nusa Penida package departing from Serangan Harbour and arriving at a private jetty.": "从 Serangan 港口出发并抵达私人码头的单人佩尼达岛西线私人套餐。",
  "Daily Departure": "每日出发",
  "Private package price shown for one guest": "所示价格为单人私人套餐",
  "One guest at the displayed price; pricing for two or more guests must be confirmed.": "所示价格适用于 1 位游客；2 位或以上价格需另行确认。",
  "Daily departure": "每日出发",
  "Beach-club access": "海滩俱乐部使用权",
  "Return boat ticket and a private car in Nusa Penida are included. Hotel transfer is not yet confirmed.": "包含往返船票及佩尼达岛私人用车。酒店接送尚未确认。",
  "Lunch is listed as included.": "列明包含午餐。",
  "Nusa Penida entrance fee is listed as included.": "列明包含佩尼达岛入岛费。",
  "A driver or guide is not specifically listed and must be confirmed.": "司机或导游未明确列出，需要确认。",
  "Suggested itinerary": "建议行程",
  "Departure from Serangan Harbour": "从 Serangan 港口出发",
  "Return journey": "返程",
  "Return boat ticket from Serangan Harbour to the private jetty in Nusa Penida": "Serangan 港口至佩尼达岛私人码头的往返船票",
  "Nusa Penida tour based on the listed itinerary": "按所列路线游览佩尼达岛",
  "Nusa Penida entrance fee": "佩尼达岛入岛费",
  "Complimentary access to Caspla Beach Club": "免费进入 Caspla 海滩俱乐部",
  "Complimentary swimming-pool access": "免费使用泳池",
  "Air-conditioned toilet facilities": "空调洗手间设施",
  "Boat waiting area at the beach club": "海滩俱乐部候船区",
  "This price is for a private package for one guest.": "此价格为 1 位游客的私人套餐。",
  "Water sports are available at the beach club. Complimentary access is not confirmed.": "海滩俱乐部提供水上活动，是否免费尚未确认。",
  "Kintamani Mount Batur Jeep Experiences": "金塔马尼巴杜尔火山吉普车体验",
  "Three ways to see the mountain.": "三种方式欣赏火山。",
  "These are Kintamani jeep experiences only—not complete Bali transportation packages.": "这些仅为金塔马尼吉普车体验，并非完整的巴厘岛交通套餐。",
  "Private jeep experiences with volcanic views": "欣赏火山景观的私人吉普车体验",
  "One jeep can accommodate a maximum of three guests.": "每辆吉普车最多乘坐 3 位游客。",
  "Prices do not include a full-day private car, hotel transfer, fuel, or a separate driver outside the jeep service.": "价格不包含全日私人用车、酒店接送、燃油或吉普车服务以外的另配司机。",
  "Afternoon Jeep Trip": "下午吉普车之旅",
  "An afternoon off-road visit to the Black Lava and Black Sand areas.": "下午越野前往黑色熔岩和黑沙区域。",
  "Mount Batur area entrance tickets": "巴杜尔火山区域门票",
  "Sunset Jeep Trip": "日落吉普车之旅",
  "A sunset-focused jeep experience with Black Lava, Black Sand, coffee, and snacks.": "以日落为主题的吉普车体验，包含黑色熔岩、黑沙、咖啡和小吃。",
  "Sunset Point": "日落观景点",
  "Coffee and snacks": "咖啡和小吃",
  "Sunrise Jeep Trip": "日出吉普车之旅",
  "An early-morning jeep experience covering sunrise, Black Lava, coffee, and breakfast.": "清晨吉普车体验，包含日出、黑色熔岩、咖啡和早餐。",
  "Sunrise viewpoint": "日出观景点",
  "Coffee break": "咖啡休息",
  "Breakfast": "早餐",
  "Maximum 3 guests": "最多 3 位游客",
  "per jeep, net": "每辆吉普车，净价",
  "Duration / schedule": "时长／时间安排",
  "Physical activity": "体力活动",
  "Clothing / equipment": "服装／装备",
  "Not included": "不包含",
  "Full-day private car, hotel transfer, fuel, or a separate driver outside the jeep service.": "全日私人用车、酒店接送、燃油或吉普车服务以外的另配司机。",
  "Comfort beyond the drive": "不止是接送，更在意舒适",
  "Personal care for your Bali day": "为你的巴厘岛旅程提供贴心照顾",
  "Considered comfort": "细致舒适",
  "The small things are": "贴心小物都已",
  "already handled.": "为你准备好。",
  "Long days feel lighter when useful essentials are within reach.": "实用物品随手可取，让一整天的旅程更轻松。",
  "Snacks": "小吃",
  "Phone charger": "手机充电器",
  "Tissues & wet wipes": "纸巾和湿纸巾",
  "Umbrella": "雨伞",
  "Small first-aid kit": "小型急救包",
  "Trash bag": "垃圾袋",
  "Sanitary pads are available in the car.": "车内备有卫生巾。",
  "A simple comfort detail for guests who need them.": "为有需要的游客准备的一份贴心细节。",
  "Clear before you book": "预订前清楚了解",
  "Payment and policies.": "付款与政策。",
  "Review the official payment details, deposit requirements, and cancellation policy before confirming your trip.": "确认行程前，请查看官方付款信息、订金要求和取消政策。",
  "Payment Information": "付款信息",
  "Bank": "银行",
  "Account number": "账号",
  "Account name": "账户名称",
  "For bank-transfer payments, please transfer only to the official Bank Mandiri account listed above.": "银行转账请仅汇至上方列出的官方 Bank Mandiri 账户。",
  "Deposit": "订金",
  "30% to confirm the reservation": "支付 30% 以确认预订",
  "Remaining balance": "剩余款项",
  "Paid on the day of the trip": "行程当天支付",
  "Accepted methods": "支持方式",
  "Bank transfer · Cash · Card · QRIS": "银行转账 · 现金 · 银行卡 · QRIS",
  "Payment security": "付款安全",
  "For your safety, do not transfer money to any other bank account. Please contact us through our official WhatsApp number if you receive different payment instructions.": "为保障资金安全，请勿转账至其他银行账户。若收到不同的付款指示，请通过我们的官方 WhatsApp 联系。",
  "Cancellation and Rescheduling": "取消与改期",
  "More than 72 hours before the trip": "行程开始前超过 72 小时",
  "The deposit is refundable.": "订金可退。",
  "Within 72 hours of the trip": "行程开始前 72 小时以内",
  "The deposit is non-refundable.": "订金不退。",
  "Rescheduling": "改期",
  "Allowed, subject to availability.": "可在有名额的情况下改期。",
  "Important Guest Information": "游客重要信息",
  "Know what to expect before you book.": "预订前了解重要事项。",
  "These details form the practical booking guide. Items still awaiting confirmation are clearly marked and will not be presented as final policy.": "以下内容为实用预订指南。仍待确认的项目会清楚标注，不会被视为最终政策。",
  "Booking and confirmation": "预订与确认",
  "Submit a package or custom-tour request through the form or official WhatsApp number.": "请通过表单或官方 WhatsApp 提交套餐或定制行程需求。",
  "We will confirm availability, the final itinerary, price, inclusions, exclusions, and pickup details in writing.": "我们会以书面方式确认名额、最终行程、价格、包含与不含项目及接送详情。",
  "A 30% deposit is required to confirm the reservation. The remaining balance is due on the day of the trip.": "需支付 30% 订金确认预订，剩余款项在行程当天支付。",
  "Messages are answered during business hours, 9:00 AM–9:00 PM Bali time (WITA).": "我们会在巴厘岛时间 09:00–21:00（WITA）营业时段回复消息。",
  "Changes, refunds, and timing": "更改、退款与时间",
  "Cancellation more than 72 hours before the trip: the deposit is refundable.": "行程开始前超过 72 小时取消：订金可退。",
  "Cancellation within 72 hours: the deposit is non-refundable.": "行程开始前 72 小时以内取消：订金不退。",
  "Rescheduling is allowed, subject to availability.": "可在有名额的情况下改期。",
  "Pickup and preparation": "接送与准备",
  "The exact pickup point and departure details will be confirmed after booking.": "预订后将确认准确接送地点与出发详情。",
  "Bring suitable clothing and footwear, sun protection, required personal medication, and activity-specific equipment when advised.": "请携带合适的衣物和鞋子、防晒用品、所需个人药物，并按提醒携带活动专用装备。",
  "Accessibility, language, and food": "无障碍、语言与饮食",
  "Disclose medical, mobility, pregnancy, allergy, accessibility, and dietary requirements before confirmation.": "确认前请说明医疗、行动不便、怀孕、过敏、无障碍及饮食需求。",
  "English, Indonesian, Simplified Chinese, Russian, Japanese, and Korean are available.": "提供英语、印尼语、简体中文、俄语、日语和韩语服务。",
  "Photography and belongings": "拍照与个人物品",
  "Guests are responsible for personal belongings unless otherwise required by applicable law.": "除适用法律另有规定外，游客需自行保管个人物品。",
  "Contact and emergencies": "联系与紧急情况",
  "Official WhatsApp and phone: +62 859-5931-3339.": "官方 WhatsApp 与电话：+62 859-5931-3339。",
  "Emergency contact: Chelyn, +62 858-2375-4807.": "紧急联系人：Chelyn，+62 858-2375-4807。",
  "Business hours: 9:00 AM–9:00 PM Bali time (WITA).": "营业时间：巴厘岛时间 09:00–21:00（WITA）。",
  "Messages are answered during business hours.": "消息将在营业时间内回复。",
  "Guest Safety Information": "游客安全须知",
  "Good trips start with clear expectations.": "安心旅程从清楚了解开始。",
  "Please read this information before requesting or confirming a service.": "申请或确认服务前，请阅读以下信息。",
  "Guests must follow the instructions of the driver, guide, boat crew, activity operator, and local authorities.": "游客必须遵守司机、导游、船员、活动运营方和当地主管部门的指示。",
  "Tour schedules and destinations may change because of weather, sea conditions, traffic, road conditions, harbour operations, volcanic activity, government restrictions, or other safety concerns.": "行程时间与目的地可能因天气、海况、交通、道路、港口运营、火山活动、政府限制或其他安全因素调整。",
  "Guests must disclose relevant medical conditions, allergies, injuries, pregnancy, mobility limitations, or other health concerns before participating.": "参加活动前，游客必须说明相关疾病、过敏、受伤、怀孕、行动限制或其他健康问题。",
  "Guests must bring their own personal medication.": "游客必须自备个人药物。",
  "Children must remain under the supervision of a parent or responsible adult.": "儿童必须始终由父母或负责的成年人照看。",
  "Guests should wear suitable clothing and footwear for the selected activities.": "游客应根据所选活动穿着合适衣物和鞋子。",
  "Safety equipment must be worn when required.": "需要时必须使用安全装备。",
  "Alcohol use or unsafe behaviour may result in removal from an activity.": "饮酒或不安全行为可能导致被取消活动资格。",
  "Snorkeling locations and manta sightings cannot be guaranteed.": "无法保证浮潜地点或看到魔鬼鱼。",
  "The operator may refuse participation when a guest’s health, condition, or behaviour creates a safety risk.": "若游客的健康状况、身体状态或行为构成安全风险，运营方可拒绝其参加。",
  "Emergency contact during the tour: Chelyn, +62 858-2375-4807.": "行程中紧急联系人：Chelyn，+62 858-2375-4807。",
  "Travel insurance is recommended.": "建议购买旅行保险。",
  "Some package cards list insurance coverage, but the provider, benefits, limits, and exclusions must be confirmed. [ADD INSURANCE INFORMATION]": "部分套餐列有保险保障，但保险提供方、保障内容、限额与除外责任必须另行确认。",
  "Sea conditions, harbour operations, steep or uneven access, cliffs, and road conditions may affect the itinerary or whether a stop is suitable.": "海况、港口运营、陡峭或不平整的通道、悬崖及道路状况可能影响行程或景点是否适合前往。",
  "Mount Batur jeep experiences": "巴杜尔火山吉普车体验",
  "Off-road terrain can be rough. Guests who are pregnant or have back, joint, mobility, or other medical concerns must disclose them before booking.": "越野路面可能颠簸。怀孕或有背部、关节、行动不便及其他健康问题的游客必须在预订前说明。",
  "Emergency and insurance": "紧急情况与保险",
  "Emergency: Chelyn, +62 858-2375-4807. Travel insurance is recommended; confirm any package-specific coverage in writing before booking.": "紧急联系人：Chelyn，+62 858-2375-4807。建议购买旅行保险；预订前请以书面方式确认套餐内的具体保障。",
  "Reviews and Trust": "评价与信任",
  "Only verified information belongs here.": "此处仅展示已核实的信息。",
  "Reviews, credentials, certifications, and partner details will be published only after they can be verified.": "评价、资质、认证和合作伙伴信息仅在核实后发布。",
  "Guest reviews": "游客评价",
  "No testimonials have been invented or published without a source.": "我们不会虚构或发布无来源的评价。",
  "Local perspective": "本地视角",
  "Chelyn plans each route around the guest’s timing, interests, comfort, and safety needs.": "Chelyn 会根据游客的时间、兴趣、舒适度和安全需求规划每条路线。",
  "Credentials and partners": "资质与合作伙伴",
  "Business or partner claims will remain unpublished until documentation is available.": "在有文件可核实前，不会发布任何商业或合作伙伴声明。",
  "Bank transfers must go only to the official Bank Mandiri account displayed in the Payment Information section.": "银行转账只能汇至付款信息中显示的官方 Bank Mandiri 账户。",
  "Review payment details": "查看付款详情",
  "Contact Link & Ko Bali": "联系 Link & Ko Bali",
  "Tell us what you want to experience.": "告诉我们你想体验什么。",
  "Share your preferred destinations, schedule, group size, and interests. We will create a personalized day-tour plan for you.": "告诉我们你喜欢的目的地、时间、人数和兴趣，我们会为你设计个性化一日游。",
  "International WhatsApp": "国际游客 WhatsApp",
  "Indonesia / Tamu lokal": "印尼本地游客",
  "Email": "电子邮箱",
  "Business hours": "营业时间",
  "9:00 AM–9:00 PM Bali time (WITA)": "巴厘岛时间 09:00–21:00（WITA）",
  "Expected response": "回复时间",
  "Messages are answered during business hours": "消息将在营业时间内回复",
  "Service area": "服务区域",
  "Bali, including selected Nusa Penida and Kintamani services": "巴厘岛，包括部分佩尼达岛和金塔马尼服务",
  "Emergency contact": "紧急联系人",
  "Connect With Us": "关注并联系我们",
  "Scan an official QR code below. Tap or click any image to open it at full size.": "扫描下方官方二维码。点击任意图片可查看大图。",
  "Scan to start a WhatsApp chat with us.": "扫码通过 WhatsApp 联系我们。",
  "Scan to connect with us on WeChat.": "扫码添加我们的微信。",
  "Scan to follow us on RedNote.": "扫码关注我们的小红书。",
  "Scan to follow us on Instagram.": "扫码关注我们的 Instagram。",
  "Open full size ↗": "查看大图 ↗",
  "Good questions": "常见问题",
  "Before you": "提交需求",
  "make a request.": "之前先了解。",
  "Anything not covered here can be confirmed directly with Chelyn.": "未在此处说明的内容可直接向 Chelyn 确认。",
  "Can I customize a tour?": "可以定制行程吗？",
  "Yes. Share your preferred destinations, dates, available time, group size, interests, budget, and any special requirements. We will prepare a suitable plan and confirm the final details in writing.": "可以。请告诉我们目的地、日期、可用时间、人数、兴趣、预算和特别需求。我们会制定合适方案并以书面方式确认最终详情。",
  "Are the tours private?": "行程是私人的吗？",
  "Private land transportation is available where it is specifically listed. Fast boats and some activities may be shared. [CONFIRM WHICH PACKAGES ARE FULLY PRIVATE OR SHARED]": "如套餐明确说明，可提供私人陆路交通。快艇和部分活动可能与其他游客共享；请在预订前确认具体安排。",
  "What is included in the price?": "价格包含什么？",
  "Each package card lists its confirmed inclusions. Your written quotation will confirm transportation, meals, tickets, guide service, and any other inclusions before payment.": "每张套餐卡会列出已确认的包含项目。付款前，书面报价会确认交通、餐食、门票、导游服务和其他包含内容。",
  "Are there additional charges?": "会有额外费用吗？",
  "Unless specifically included, parking, toll-road fees, meals, activities, and entrance tickets are paid separately by the guest. Any other extra cost must be confirmed in the written quotation.": "除非明确包含，停车费、高速费、餐食、活动和门票由游客另付。其他额外费用必须在书面报价中确认。",
  "Is transportation included?": "包含交通吗？",
  "It depends on the package. Only transportation specifically listed under Inclusions is included. Hotel pickup areas and exact meeting points may still require confirmation.": "视套餐而定。只有在费用包含中明确列出的交通才包含。酒店接送区域和准确集合地点仍可能需要确认。",
  "Where will I be picked up?": "在哪里接我？",
  "Enter your hotel or pickup location in the request form. We will confirm the pickup point, coverage area, and any extra transfer cost before your booking is confirmed.": "请在表单填写酒店或接送地点。确认预订前，我们会确认接送点、服务范围和可能产生的额外接送费。",
  "Can children join?": "儿童可以参加吗？",
  "Children may join suitable tours under adult supervision. Some Nusa Penida packages list a 20% discount for children aged 0–3. [ADD CHILD-SEAT AVAILABILITY] [CONFIRM ACTIVITY-SPECIFIC AGE RESTRICTIONS]": "儿童可在成人照看下参加适合的行程。部分佩尼达岛套餐为 0–3 岁儿童提供 20% 优惠。儿童座椅和具体活动年龄限制请在预订前确认。",
  "Are the tours suitable for elderly guests?": "行程适合长者吗？",
  "Suitability depends on the route, access conditions, and the guest’s mobility and health. Disclose any mobility or medical requirements so we can assess the itinerary before confirmation.": "是否适合取决于路线、通行条件、游客行动能力和健康状况。请说明行动或医疗需求，以便我们在确认前评估行程。",
  "What happens during bad weather?": "天气不好时怎么办？",
  "Routes, activities, or departure points may change for safety. [ADD WEATHER CANCELLATION, RESCHEDULING, AND REFUND POLICY]": "为确保安全，路线、活动或出发点可能调整。天气导致的取消、改期和退款安排请在预订前确认。",
  "What should I wear?": "应该穿什么？",
  "Wear suitable clothing and secure footwear for the selected activities. Bring sun protection and any personal medication. Package-specific equipment requirements must be confirmed before departure.": "请根据活动穿着合适衣物和稳固鞋子，并携带防晒用品及个人药物。套餐专用装备要求须在出发前确认。",
  "Do I need travel insurance?": "需要旅行保险吗？",
  "Travel insurance is recommended. Some packages list insurance coverage, but the provider, benefits, exclusions, and limits still require confirmation. [ADD GENERAL INSURANCE INFORMATION]": "建议购买旅行保险。部分套餐列有保险，但提供方、保障内容、除外责任和限额仍需确认。",
  "Can you accommodate dietary restrictions?": "可以照顾特殊饮食需求吗？",
  "Tell us about allergies, dietary restrictions, or preferences in the request form. We will confirm what can be accommodated before the trip.": "请在表单说明过敏、饮食限制或偏好。出发前我们会确认可安排的内容。",
  "How do I pay?": "如何付款？",
  "A 30% deposit confirms the reservation. The remaining balance is due on the trip day. Accepted methods are bank transfer, cash, card, and QRIS. Bank transfers must go only to the official Bank Mandiri account shown on this website.": "支付 30% 订金即可确认预订，余款在行程当天支付。支持银行转账、现金、银行卡和 QRIS。银行转账只能汇至本网站显示的官方 Bank Mandiri 账户。",
  "What is the cancellation policy?": "取消政策是什么？",
  "The deposit is refundable when cancellation is made more than 72 hours before the trip. Within 72 hours, the deposit is non-refundable. Rescheduling is allowed subject to availability; any fee or deadline still needs confirmation.": "行程开始前超过 72 小时取消可退订金；72 小时以内取消订金不退。可在有名额时改期，相关费用或期限需确认。",
  "How quickly will I receive my custom plan?": "多久能收到定制方案？",
  "We review requests and reply through WhatsApp or email during business hours, 9:00 AM–9:00 PM Bali time (WITA).": "我们会在巴厘岛时间 09:00–21:00（WITA）营业时段审核需求，并通过 WhatsApp 或电子邮箱回复。",
  "Plan Your Bali Trip With Us": "与我们规划你的巴厘岛之旅",
  "Tell us what": "告诉我们你的",
  "your trip needs.": "旅程需要什么。",
  "Every guest travels differently. Tell us your preferred destinations, available dates, group size, interests, and budget. We will help arrange a personalized itinerary based on your needs.": "每位游客的旅行方式都不同。请告诉我们目的地、日期、人数、兴趣和预算，我们会按你的需求安排个性化行程。",
  "Preferred destinations and activities": "喜欢的目的地和活动",
  "Available time and travel schedule": "可用时间和旅行安排",
  "Group size and estimated budget": "人数和预算",
  "Children, elderly guests, and accessibility requirements": "儿童、长者和无障碍需求",
  "Pickup and drop-off locations": "接送地点",
  "Dietary needs and special occasions": "饮食需求和特别纪念日",
  "Messages are answered from 9:00 AM to 9:00 PM Bali time (WITA).": "消息将在巴厘岛时间 09:00–21:00（WITA）回复。",
  "Thank you for contacting Link & Ko Bali.": "感谢联系 Link & Ko Bali。",
  "We will review your request and contact you through WhatsApp or email.": "我们会审核你的需求，并通过 WhatsApp 或电子邮箱联系你。",
  "WhatsApp has opened with your request details. Tap Send in WhatsApp to complete your inquiry.": "WhatsApp 已打开并填入你的需求详情。请点击发送完成咨询。",
  "Send another request": "再次提交需求",
  "Selected package": "已选套餐",
  "Full name": "姓名",
  "WhatsApp number": "WhatsApp 号码",
  "Email address": "电子邮箱",
  "Travel date": "出行日期",
  "Number of adults": "成人数量",
  "Number and ages of children": "儿童数量与年龄",
  "Hotel or pickup location": "酒店或接送地点",
  "Drop-off location": "送达地点",
  "Available time or schedule": "可用时间或行程安排",
  "Preferred destinations": "喜欢的目的地",
  "Estimated budget": "预算",
  "Transportation requirements": "交通需求",
  "Dietary requirements": "饮食需求",
  "Medical or mobility considerations": "医疗或行动需求",
  "Special occasion": "特别纪念日",
  "Additional requests": "其他需求",
  "Example: 2 children, ages 3 and 7": "例如：2 名儿童，3 岁和 7 岁",
  "Same as pickup, or another location": "与接送地点相同，或填写其他地点",
  "Example: 8:00 AM–6:00 PM": "例如：08:00–18:00",
  "Places or package you are interested in": "感兴趣的地点或套餐",
  "Snorkeling, beach, temple, food, photography…": "浮潜、海滩、寺庙、美食、摄影……",
  "Airport transfer, half day, full day…": "机场接送、半日、全日……",
  "Allergies or preferences": "过敏或饮食偏好",
  "Tell us what support you need": "请告诉我们你需要的协助",
  "Birthday, honeymoon, proposal, or celebration": "生日、蜜月、求婚或庆祝活动",
  "Anything else we should know?": "还有其他需要我们了解的吗？",
  "I confirm that I have read the safety information and have disclosed any relevant medical, mobility, or accessibility requirements.": "我确认已阅读安全须知，并已说明相关医疗、行动或无障碍需求。",
  "Before submitting": "提交前",
  "Unless specifically included in your final written quotation, additional costs and services remain excluded.": "除非最终书面报价明确包含，否则额外费用和服务均不包含。",
  "Request My Custom Plan": "提交我的定制需求",
  "Submitting this form opens WhatsApp with your details. Your reservation is not confirmed until availability, price, and the deposit are confirmed.": "提交表单后将打开 WhatsApp 并填入你的信息。在名额、价格和订金确认前，预订尚未成立。",
  "Ready to Plan Your Bali Experience?": "准备好规划巴厘岛体验了吗？",
  "Let’s turn your list into a realistic Bali plan.": "让我们把你的愿望清单变成可行的巴厘岛行程。",
  "Tell us where you would like to go, how many people are travelling, and your preferred budget. We will help create a suitable plan for your Bali trip.": "告诉我们想去哪里、出行人数和预算，我们会协助制定合适的巴厘岛行程。",
  "Private trips with Chelyn.": "与 Chelyn 一起享受私人行程。",
  "Packages": "套餐",
};

export const zhPending: Record<string, string> = {
  "ADD DURATION": "补充时长",
  "ADD STARTING AND FINISHING TIME": "补充开始与结束时间",
  "CONFIRM WHETHER PRICE IS PER PERSON OR PER GROUP": "确认价格按人还是按团计算",
  "ADD MINIMUM AND MAXIMUM NUMBER OF GUESTS": "补充最少和最多游客人数",
  "ADD OPERATING DAYS": "补充开放日期",
  "ADD RECOMMENDED CLOTHING OR EQUIPMENT": "补充建议服装或装备",
  "ADD PHYSICAL ACTIVITY LEVEL": "补充体力强度",
  "ADD AGE RESTRICTIONS, IF APPLICABLE": "如适用，补充年龄限制",
  "CONFIRM DEPARTURE HARBOUR": "确认出发港口",
  "CONFIRM HOTEL PICKUP AREAS": "确认酒店接送区域",
  "CONFIRM INSURANCE COVERAGE DETAILS": "确认保险保障详情",
  "CONFIRM WHETHER A RESCHEDULING FEE OR TIME LIMIT APPLIES": "确认改期费用或期限",
  "ADD EMAIL ADDRESS": "补充电子邮箱",
};
